### PR TITLE
[Deps] Update cozy-indexer to v0.0.13

### PR DESCRIPTION
**Pull request by aenario**
See https://github.com/cozy/cozy-indexer/pull/4

### CODE REVIEW

**Comment by nono** [comment]
@aenario there is an error on the travis build, with node4 (a timeout on indexation). Is it normal?

**Comment by aenario** [comment]
It is not normal, i am restarting the test to see if it's an intermittent and will investigate if not

**Comment by aenario** [comment]
Ok, its an intermittent. I will increase this timeout.

**Comment by nono** [comment]
Thanks @aenario

**Pull request merged**
