### PR TITLE
Fix node 5 build on travis

### PR DESCRIPTION
**Pull request by nono**

### CODE REVIEW

**Comment by nono** [comment]
The failures on travis are a known bug. @poupotte works on it on #192

**Comment by kosssi** [comment]
@nono can you document more your PR why you install this version of gcc ?

**Comment by nono** [comment]
@kosssi it's documented on travis: https://docs.travis-ci.com/user/languages/javascript-with-nodejs/#Node.js-v4-%28or-io.js-v3%29-compiler-requirements

**Comment by kosssi** [comment]
:+1:

**Pull request merged**
