### PR TITLE
[DO NOT MERGE] Add WWW-Authenticate header on 401

### PR DESCRIPTION
**Pull request by aenario**
This might allow cozysdk.getFileURL to work in prod.

### CODE REVIEW

**Comment by m4dz** [comment]
Nice :). Will it be sufficient to get an `Authorization` header that can be extracted from https://github.com/cozy/cozy-proxy/blob/master/server/controllers/devices.coffee#L285?

**Comment by aenario** [comment]
@m4dz @flyingrub The problem is browser appears not to use the URL embeded credentials, we need to test if this change (ie. the ds sending the proper Authenticate error along the 401 error code) solve the issue in chrome and firefox.

Otherwise, we will have no choice but to accept credentials both as header or GET variable.
```
http://xxxx.cozycloud.cc/ds-api/file?Authorization=
```

**Comment by m4dz** [comment]
Al'right. Telll me if you need me to test some parts!

**Comment by flyingrub** [comment]
can be closed :)

**Comment by m4dz** [comment]
@flyingrub not sure: the way @aenario proposes here to send a Realm Auth header to force auth seems a way more cleaner than passing in a query params. I suggest we keep this one open and make some more tests :smiley:

**Pull request closed without merging**
