### PR TITLE
Add lint in travis build

### PR DESCRIPTION
**Pull request by kosssi**

### CODE REVIEW

**Comment by aenario** [comment]
Tests are passing except for a known intermittent, I notified zoe, so she can take a look and will restart them afer

**Comment by aenario** [comment]
My bad, tests are actually failing with node4, @kosssi can you take a look ?
https://travis-ci.org/cozy/cozy-data-system/jobs/100302284#L564-L567
https://travis-ci.org/cozy/cozy-data-system/jobs/100302284#L777-L778

**Comment by kosssi** [comment]
@aenario I'm speaking with zoe and I will update my last commit for add security and fix this test.

**Comment by kosssi** [comment]
@aenario @nono travis is good. This error will be fix by @poupotte in another PR

**Comment by poupotte** [comment]
It's ok for me :+1:

**Comment by poupotte** [comment]
@aenario , @nono , this PR is ok for you ?

**Comment by nono** [comment]
:+1:

**Comment by poupotte** [comment]
Thanks @nono  :)

**Pull request merged**
