### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by nono**

### CODE REVIEW

**Comment by nono** [comment]
@aenario I removed connectors as it looks like dead code that use the old indexer. Can you confirm that is no longer used?

**Comment by nono** [comment]
Tests have failed only on thumbs. It's a known failure (see #192), cc: @poupotte.

**Comment by kosssi** [comment]
@nono it's normal you want merge it to master ?

**Comment by aenario** [comment]
This was merged into development. 
Master release later today.

**Comment by nono** [comment]
@kosssi you are right, it was a mistake. It was meant to be merged in development.

**Pull request closed without merging**
