### PR TITLE
[DONT MERGE YET] Feature/request all

### PR DESCRIPTION
**Pull request by aenario**
Rebase of poupotte/feature/request-all on current master for tracking

Todo : 
- [ ] check on a normal cozy if this works / is efficient
- [ ] check tests pass
- [ ] breaks cozy-fixtures, fix cozy-fixtures or here
- [ ] remove nodetime & v8-profiler
- [ ] re-run travis on all apps after merging to ensure this doesn't break any app

### CODE REVIEW

**Comment by frankrousseau** [comment]
@aenario What should we do with that PR?

**Comment by frankrousseau** [comment]
@aenario @clochix @jsilvestre @poupotte What should we do with that PR?

**Comment by aenario** [comment]
Well, cozy-emails is running quite fine without (still not sure why), some user complained about slow cozy after first import, but as it fix itself after a few minutes so most are OK. Anyway, because the indexer is the slowest part, it's probably where we should focus our efforts.

So I'd say we close it for now (as it will probably cause more instability in the sort run). Once all apps are all running  cozydb, it will be easier to enhance progressively how we request the DS (no emit(doc), some special handling of the all request, ect ...) and reintroduce this PR in ~ three month.

**Comment by frankrousseau** [comment]
Ok thank you for the information.

**Pull request closed without merging**
