### PR TITLE
[WIP] Fix tests for thumb updating

### PR DESCRIPTION
**Pull request by poupotte**
Contains https://github.com/cozy/cozy-data-system/pull/188

### CODE REVIEW

**Comment by frankrousseau** [comment]
@poupotte, tests are still failing.

**Comment by poupotte** [comment]
@frankrousseau I know (they still fail randomly), but I don't understand why for the moment.

**Comment by kosssi** [comment]
no it's green :dancer:

**Comment by poupotte** [comment]
@kosssi , yes but not always :(

**Pull request closed without merging**
